from datetime import datetime

from tgk_trading.backtest.drawdown import (
  calculate_max_drawdown,
  calculate_max_drawdown_percent
)
from tgk_trading.backtest.simulated_broker import SimulatedBroker
from tgk_trading.backtest.trade_statistics import calculate_trade_statistics
from tgk_trading.backtest.result import BacktestResult
from tgk_trading.domain.account import Account
from tgk_trading.domain.market_data import CandleSeries
from tgk_trading.domain.order import Order, OrderSide, OrderType
from tgk_trading.domain.position import Position
from tgk_trading.domain.signal import SignalType
from tgk_trading.domain.trade import Trade
from tgk_trading.domain.pnl import calculate_unrealized_pnl
from tgk_trading.strategies.base import Strategy


class BacktestEngine:

  def __init__(
    self,
    strategy: Strategy,
    initial_balance: float
  ):
    self._strategy = strategy
    self._account = Account(initial_balance)
    self._broker = SimulatedBroker()
    self._data = CandleSeries()
    self._initial_balance = initial_balance
    self._realized_pnl = 0.0
    self._position_entry_times: dict[Position, datetime] = {}
    self._trades: list[Trade] = []
    self._pending_signal = SignalType.NONE

  def _calculate_unrealized_pnl(
    self,
    current_price: float
  ) -> float:

    total_pnl = 0.0

    for position in self._account.positions():
      total_pnl += calculate_unrealized_pnl(
        side=position.side,
        entry_price=position.entry_price,
        current_price=current_price,
        quantity=position.quantity
      )

    return total_pnl

  def run(self, candles) -> BacktestResult:
    equity_curve: list[float] = []

    for candle in candles:
      self._data.append(candle)

      # Execute the signal generated by the previous closed candle
      # at the current candle's open, matching MT5's behavior.
      if self._pending_signal != SignalType.NONE:
        self._process_signal(
          signal_type=self._pending_signal,
          price=candle.open
        )
        self._pending_signal = SignalType.NONE

      # Generate a signal from the current closed candle.
      # It will be executed on the next candle.
      signal = self._strategy.on_candle(self._data)
      self._pending_signal = signal.type

      unrealized_pnl = self._calculate_unrealized_pnl(
        current_price=candle.close
      )

      equity = (
        self._account.balance()
        + unrealized_pnl
      )

      equity_curve.append(equity)

    current_candle = self._data.current()

    if current_candle is None:
      raise ValueError("Cannot run backtest with no candles")

    final_price = current_candle.close

    unrealized_pnl = self._calculate_unrealized_pnl(
      current_price=final_price
    )

    equity = (
      self._account.balance()
      + unrealized_pnl
    )

    max_drawdown = calculate_max_drawdown(equity_curve)
    max_drawdown_percent = calculate_max_drawdown_percent(equity_curve)

    return BacktestResult(
      initial_balance=self._initial_balance,
      final_balance=self._account.balance(),
      realized_pnl=self._realized_pnl,
      unrealized_pnl=unrealized_pnl,
      equity=equity,
      equity_curve=equity_curve,
      max_drawdown=max_drawdown,
      max_drawdown_percent=max_drawdown_percent,
      trades=list(self._trades),
      trade_statistics=calculate_trade_statistics(self._trades)
    )

  def _process_signal(
    self,
    signal_type: SignalType,
    price: float
  ):
    if signal_type == SignalType.NONE:
      return

    current_position = self._get_current_position()

    if current_position is not None:

      if (
        signal_type == SignalType.BUY
        and current_position.side.value == "BUY"
      ):
        return

      if (
        signal_type == SignalType.SELL
        and current_position.side.value == "SELL"
      ):
        return

      closed = self._broker.close_position(
        position=current_position,
        price=price
      )

      self._account.remove_position(current_position)
      self._account.apply_realized_pnl(closed.pnl)

      self._realized_pnl += closed.pnl

      entry_time = self._position_entry_times.pop(
        current_position
      )

      self._trades.append(Trade(
        side=closed.position.side,
        quantity=closed.position.quantity,
        entry_time=entry_time,
        entry_price=closed.position.entry_price,
        exit_time=self._data.current().time,
        exit_price=closed.exit_price,
        pnl=closed.pnl
      ))

    order = self._create_order(signal_type)

    position = self._broker.execute_order(
      order=order,
      price=price
    )

    self._account.add_position(position)
    self._position_entry_times[position] = self._data.current().time

  def _create_order(
    self,
    signal_type: SignalType
  ) -> Order:

    if signal_type == SignalType.BUY:
      side = OrderSide.BUY

    elif signal_type == SignalType.SELL:
      side = OrderSide.SELL

    else:
      raise ValueError(
        f"Cannot create order from signal: {signal_type}"
      )

    return Order(
      type=OrderType.MARKET,
      side=side,
      quantity=1.0
    )

  def _get_current_position(self) -> Position | None:
    positions = self._account.positions()

    if not positions:
      return None

    return positions[0]
