#ifndef MQL_AUTO_FORWARDS_INCLUDED_9A2CFB7105D7A3DE
#define MQL_AUTO_FORWARDS_INCLUDED_9A2CFB7105D7A3DE
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in /Users/tachagon/Documents/13_Trade/1_Bot/BotTradeFramework/Experts/EMA_Cross_Retest.mq5

#line 109 "/Users/tachagon/Documents/13_Trade/1_Bot/BotTradeFramework/Experts/EMA_Cross_Retest.mq5"
bool H1CrossUp();
#line 130 "/Users/tachagon/Documents/13_Trade/1_Bot/BotTradeFramework/Experts/EMA_Cross_Retest.mq5"
bool H1CrossDown();
#line 153 "/Users/tachagon/Documents/13_Trade/1_Bot/BotTradeFramework/Experts/EMA_Cross_Retest.mq5"
bool BuyRetest();
#line 166 "/Users/tachagon/Documents/13_Trade/1_Bot/BotTradeFramework/Experts/EMA_Cross_Retest.mq5"
bool SellRetest();
#line 181 "/Users/tachagon/Documents/13_Trade/1_Bot/BotTradeFramework/Experts/EMA_Cross_Retest.mq5"
bool BuyA();
#line 199 "/Users/tachagon/Documents/13_Trade/1_Bot/BotTradeFramework/Experts/EMA_Cross_Retest.mq5"
bool SellA();
#line 219 "/Users/tachagon/Documents/13_Trade/1_Bot/BotTradeFramework/Experts/EMA_Cross_Retest.mq5"
bool BuyB();
#line 234 "/Users/tachagon/Documents/13_Trade/1_Bot/BotTradeFramework/Experts/EMA_Cross_Retest.mq5"
bool SellB();
#line 251 "/Users/tachagon/Documents/13_Trade/1_Bot/BotTradeFramework/Experts/EMA_Cross_Retest.mq5"
bool IsH4BullTrend();
#line 260 "/Users/tachagon/Documents/13_Trade/1_Bot/BotTradeFramework/Experts/EMA_Cross_Retest.mq5"
bool IsH4BearTrend();
#line 271 "/Users/tachagon/Documents/13_Trade/1_Bot/BotTradeFramework/Experts/EMA_Cross_Retest.mq5"
void ProcessStateMachine();

#endif
